{{- $fullName := include "logscale-content.fullname" . -}}
{{- $labels := include "logscale-content.labels" . -}}
{{- range .Values.secrets }}
{{- $crName := print $fullName "-" .name  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $crName }}
  labels:
    {{- $labels | nindent 4 }}  
data:
{{ toYaml .data | indent 4 }}
{{- end }}